version: "3.8"
services:
  web:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    volumes:
      - "/app/build"
      - "/app/node_modules"
      - ".:/app"
